### PR TITLE
Update quiz.m

### PR DESCRIPTION
**Pull request by SathyaseelanRamachandran**
Demo of table quiz in MATLAB.

function finalStr = matrix_table(matrixName, matrix)
    numericalFound = strfind(matrix{1, 1}, 'NUMERICAL');
    finalStr = strcat( ...
    '    <table><tr>', ...
    '      <td style="vertical-align: center;">', matrixName, '&nbsp;=&nbsp;</td>', ...
    '      <td style="border: 1px solid #000; border-right:0px;">&nbsp;</td>', ...

### CODE REVIEW

**Review by Tomyzon1728 — APPROVED** [review]
Great functionalities added, good job .
Make code more readable  by making use of comments

**Comment by Tomyzon1728** [comment]
Great work , I've explained things to add next time in the review section

**Review by Tomyzon1728 — APPROVED** [review]

**Review by Tomyzon1728 — APPROVED** [review]

**Review by Tomyzon1728 — APPROVED** [review]
Good job

**Comment by SathyaseelanRamachandran** [comment]
thank you for comments. will analyse with code readability and quality as well

**Pull request merged**
